"""Versioned extraction specification audited against the frozen G0 unit index.

The specification fixes membership and identity; text is re-extracted from DOCX.
Changing this specification is a source-freeze migration requiring human review.
Governance hash regeneration cannot change it.
"""

from __future__ import annotations

from typing import Any

EXTRACTION_BINDINGS: list[dict[str, Any]] = [
    {
        "unit_id": "S4A-2026-000",
        "source_location": {"visual_reference": "page header / template title"},
        "structural_location": {
            "document_part": "word/header1.xml",
            "paragraph_index": 1,
            "table_index": None,
            "row": None,
            "column": None,
            "paragraph": None,
        },
        "normalization_method": "LINE_BREAK_TO_SPACE",
        "authority_required": True,
    },
    {
        "unit_id": "S4A-2026-001",
        "source_location": {"table_index": 0, "row": 1, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 1,
            "table_index": 0,
            "row": 1,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-002",
        "source_location": {"table_index": 0, "row": 3, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 3,
            "table_index": 0,
            "row": 3,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-003",
        "source_location": {"table_index": 0, "row": 5, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 5,
            "table_index": 0,
            "row": 5,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-004",
        "source_location": {"table_index": 0, "row": 7, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 7,
            "table_index": 0,
            "row": 7,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-005",
        "source_location": {"table_index": 0, "row": 9, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 9,
            "table_index": 0,
            "row": 9,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-006",
        "source_location": {"table_index": 0, "row": 9, "column": 0, "paragraph": 1},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 10,
            "table_index": 0,
            "row": 9,
            "column": 0,
            "paragraph": 1,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-007",
        "source_location": {"table_index": 0, "row": 11, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 12,
            "table_index": 0,
            "row": 11,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-008",
        "source_location": {"table_index": 0, "row": 13, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 14,
            "table_index": 0,
            "row": 13,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-009",
        "source_location": {"table_index": 0, "row": 15, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 16,
            "table_index": 0,
            "row": 15,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-010",
        "source_location": {"table_index": 0, "row": 17, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 18,
            "table_index": 0,
            "row": 17,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-011",
        "source_location": {"table_index": 0, "row": 19, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 21,
            "table_index": 0,
            "row": 19,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-012",
        "source_location": {"table_index": 0, "row": 19, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 22,
            "table_index": 0,
            "row": 19,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-013",
        "source_location": {"table_index": 0, "row": 19, "column": 2, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 23,
            "table_index": 0,
            "row": 19,
            "column": 2,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-014",
        "source_location": {"table_index": 0, "row": 21, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 27,
            "table_index": 0,
            "row": 21,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-015",
        "source_location": {"table_index": 0, "row": 21, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 28,
            "table_index": 0,
            "row": 21,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-016",
        "source_location": {"table_index": 0, "row": 21, "column": 2, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 29,
            "table_index": 0,
            "row": 21,
            "column": 2,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-017",
        "source_location": {"table_index": 0, "row": 23, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 33,
            "table_index": 0,
            "row": 23,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-018",
        "source_location": {"table_index": 0, "row": 23, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 34,
            "table_index": 0,
            "row": 23,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-019",
        "source_location": {"table_index": 0, "row": 23, "column": 2, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 35,
            "table_index": 0,
            "row": 23,
            "column": 2,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-020",
        "source_location": {"table_index": 0, "row": 25, "column": 2, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 41,
            "table_index": 0,
            "row": 25,
            "column": 2,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-021",
        "source_location": {"table_index": 0, "row": 27, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 45,
            "table_index": 0,
            "row": 27,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-022",
        "source_location": {"table_index": 0, "row": 27, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 46,
            "table_index": 0,
            "row": 27,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-023",
        "source_location": {"table_index": 0, "row": 27, "column": 2, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 47,
            "table_index": 0,
            "row": 27,
            "column": 2,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-024",
        "source_location": {"table_index": 0, "row": 29, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 51,
            "table_index": 0,
            "row": 29,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-025",
        "source_location": {"table_index": 0, "row": 29, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 52,
            "table_index": 0,
            "row": 29,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-026",
        "source_location": {"table_index": 0, "row": 29, "column": 2, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 53,
            "table_index": 0,
            "row": 29,
            "column": 2,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-027",
        "source_location": {"table_index": 0, "row": 29, "column": 2, "paragraph": 1},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 54,
            "table_index": 0,
            "row": 29,
            "column": 2,
            "paragraph": 1,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-028",
        "source_location": {"table_index": 0, "row": 29, "column": 2, "paragraph": 2},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 55,
            "table_index": 0,
            "row": 29,
            "column": 2,
            "paragraph": 2,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-029",
        "source_location": {"table_index": 0, "row": 29, "column": 2, "paragraph": 3},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 56,
            "table_index": 0,
            "row": 29,
            "column": 2,
            "paragraph": 3,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-030",
        "source_location": {"table_index": 0, "row": 29, "column": 2, "paragraph": 4},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 57,
            "table_index": 0,
            "row": 29,
            "column": 2,
            "paragraph": 4,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-031",
        "source_location": {"table_index": 0, "row": 29, "column": 2, "paragraph": 5},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 58,
            "table_index": 0,
            "row": 29,
            "column": 2,
            "paragraph": 5,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-032",
        "source_location": {"table_index": 0, "row": 31, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 62,
            "table_index": 0,
            "row": 31,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-033",
        "source_location": {"table_index": 0, "row": 31, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 63,
            "table_index": 0,
            "row": 31,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-034",
        "source_location": {"table_index": 0, "row": 33, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 68,
            "table_index": 0,
            "row": 33,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-035",
        "source_location": {"table_index": 0, "row": 33, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 69,
            "table_index": 0,
            "row": 33,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-036",
        "source_location": {"table_index": 0, "row": 35, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 74,
            "table_index": 0,
            "row": 35,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-037",
        "source_location": {"table_index": 0, "row": 37, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 80,
            "table_index": 0,
            "row": 37,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-038",
        "source_location": {"table_index": 0, "row": 39, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 86,
            "table_index": 0,
            "row": 39,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-039",
        "source_location": {"table_index": 0, "row": 41, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 92,
            "table_index": 0,
            "row": 41,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-040",
        "source_location": {"table_index": 0, "row": 41, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 93,
            "table_index": 0,
            "row": 41,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-041",
        "source_location": {"table_index": 0, "row": 43, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 96,
            "table_index": 0,
            "row": 43,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-042",
        "source_location": {"table_index": 0, "row": 43, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 97,
            "table_index": 0,
            "row": 43,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-043",
        "source_location": {"table_index": 0, "row": 45, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 100,
            "table_index": 0,
            "row": 45,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-044",
        "source_location": {"table_index": 0, "row": 45, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 101,
            "table_index": 0,
            "row": 45,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-045",
        "source_location": {"table_index": 0, "row": 47, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 104,
            "table_index": 0,
            "row": 47,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-046",
        "source_location": {"table_index": 0, "row": 47, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 105,
            "table_index": 0,
            "row": 47,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-047",
        "source_location": {"table_index": 0, "row": 49, "column": 0, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 108,
            "table_index": 0,
            "row": 49,
            "column": 0,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-048",
        "source_location": {"table_index": 0, "row": 49, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 109,
            "table_index": 0,
            "row": 49,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-049",
        "source_location": {"table_index": 0, "row": 51, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 113,
            "table_index": 0,
            "row": 51,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-050",
        "source_location": {"table_index": 0, "row": 53, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 119,
            "table_index": 0,
            "row": 53,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-051",
        "source_location": {"table_index": 0, "row": 55, "column": 1, "paragraph": 0},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 124,
            "table_index": 0,
            "row": 55,
            "column": 1,
            "paragraph": 0,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
    {
        "unit_id": "S4A-2026-052",
        "source_location": {"table_index": 0, "row": 56, "column": 0, "paragraph": 1},
        "structural_location": {
            "document_part": "word/document.xml",
            "paragraph_index": 126,
            "table_index": 0,
            "row": 56,
            "column": 0,
            "paragraph": 1,
        },
        "normalization_method": "NONE",
        "authority_required": False,
    },
]
