"""Authored G2 Finnish synthesis decisions. Not human approval."""

from __future__ import annotations

from typing import Any

# unit_id, classification, candidate_fi, meaningful_difference, rationale,
# remaining uncertainty, human decision references.
DECISIONS: tuple[dict[str, Any], ...] = (
    {
        "unit_id": "S4A-2026-000",
        "classification": "SELECT_B",
        "candidate_fi": "Tukea antavan ja palliatiivisen hoidon tunnusmerkkityökalu (SPICT-4ALL-……)",
        "meaningful_difference": "A uses tukihoidon and adds tarpeen tunnistamisen. B uses tukea antavan and tunnusmerkkityökalu. Both keep SPICT-4ALL-…… verbatim.",
        "source_fidelity_rationale": "Indicators Tool is a tool of indicators/tunnusmerkit, not a needs-assessment claim. tukihoito can narrow supportive care toward oncology supportive treatment. B preserves the instrument name without that addition or narrowing.",
        "remaining": "No approved Finnish project term for supportive care. Title authority remains unresolved and publication-blocking; this is translation evidence only.",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-001",
        "classification": "COMBINE_A_B",
        "candidate_fi": "SPICT auttaa meitä etsimään ihmisiä, joilla on elinikää lyhentäviä terveydentiloja ja joiden terveydentila on heikentynyt. Nämä ihmiset tarvitsevat nyt enemmän apua ja hoitoa sekä suunnitelman tulevasta hoidosta.",
        "meaningful_difference": "look for: A löytämään vs B etsimään. Future care plan: A tulevasta hoidosta vs B tulevaa hoitoa varten. Both apply T-002 and terveydentila on heikentynyt.",
        "source_fidelity_rationale": "look for is etsiä, not find. Current help/care is kept distinct from a plan for future care. T-002 and the recorded less-well wording are preserved.",
        "remaining": "",
        "human_decision_refs": ["T-002", "less well: terveydentila on heikentynyt"],
    },
    {
        "unit_id": "S4A-2026-002",
        "classification": "SELECT_B",
        "candidate_fi": "Onko tällä henkilöllä merkkejä huonosta terveydentilasta tai terveysongelmia, jotka pahenevat?",
        "meaningful_difference": "A attaches pahenevia as an adjective on health problems. B keeps a relative clause that are getting worse.",
        "source_fidelity_rationale": "The source relative clause that are getting worse is preserved as jotka pahenevat without converting it into a different problem category.",
        "remaining": "The English relative clause can attach to health problems or to both alternatives; Finnish follows the nearest-antecedent reading.",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-003",
        "classification": "SELECT_B",
        "candidate_fi": "Kiireellinen tai päivystyksellinen sairaalaan otto(t) tai käynnit.",
        "meaningful_difference": "A adds yksi tai useampi and singularizes visits. B keeps urgent or emergency, optional plural (s) as (t), and plural visits.",
        "source_fidelity_rationale": "A adds a count paraphrase not in the source. B preserves the alternatives and the optional-plural marker.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-004",
        "classification": "COMBINE_A_B",
        "candidate_fi": "Toimintakyky on heikentynyt tavanomaisissa toimissa; vointi ei ole yhtä hyvä kuin ennen.\n(Henkilö viettää usein yli puolet päivästä vuoteessa tai tuolissa.)",
        "meaningful_difference": "usual: A tavallisissa vs B tavanomaisissa. not as well: A vointi vs B kunnossa. stays: A viettää vs B on.",
        "source_fidelity_rationale": "Recorded toimintakyky on heikentynyt is kept with tavanomaisissa toimissa for usual activities. vointi preserves not as well without adding fitness. viettää preserves stays.",
        "remaining": "",
        "human_decision_refs": ["less able to manage usual activities: toimintakyky on heikentynyt"],
    },
    {
        "unit_id": "S4A-2026-005",
        "classification": "SELECT_A",
        "candidate_fi": "Tarvitsee muilta enemmän apua ja hoitoa lisääntyvien fyysisen terveyden ja/tai mielenterveyden ongelmien vuoksi.",
        "meaningful_difference": "A keeps physical and/or mental health problems. B uses ruumiillisten and drops health from the physical arm.",
        "source_fidelity_rationale": "The source is physical and/or mental health problems, with ja/tai. A's fyysisen terveyden ja/tai mielenterveyden ongelmien preserves both health arms.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-006",
        "classification": "SELECT_A",
        "candidate_fi": "Henkilöstä huolehtiva ihminen tarvitsee enemmän apua ja tukea.",
        "meaningful_difference": "A huolehtiva ihminen vs B hoitava läheinen.",
        "source_fidelity_rationale": "carer is not necessarily a close relative or a care-giving professional. A's broader person who looks after the person avoids omaishoitaja narrowing and B's läheinen addition.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-007",
        "classification": "SELECT_B",
        "candidate_fi": "On selvästi laihtunut muutaman viime kuukauden aikana; tai pysyy liian laihana.",
        "meaningful_difference": "few months: A viime kuukausien vs B muutaman viime kuukauden. stays: A on edelleen vs B pysyy.",
        "source_fidelity_rationale": "few is preserved as muutaman, and stays as pysyy rather than still is.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-008",
        "classification": "SELECT_A",
        "candidate_fi": "Hänellä on hankalia oireita suurimman osan ajasta, vaikka hänen terveysongelmiaan hoidetaan hyvin.",
        "meaningful_difference": "A keeps a person subject (Has / their). B is impersonal.",
        "source_fidelity_rationale": "The source ascribes troublesome symptoms to a person despite good treatment of their health problems.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-009",
        "classification": "COMBINE_A_B",
        "candidate_fi": "Henkilö (tai perhe) pyytää palliatiivista hoitoa; valitsee hoidon vähentämisen, lopettamisen tai ottamatta jättämisen; tai toivoo keskittymistä elämänlaatuun.",
        "meaningful_difference": "not have: A pidättäytymisen vs B ottamatta jättämisen. wishes: A toivoo vs B haluaa.",
        "source_fidelity_rationale": "reduce, stop or not have are three alternatives. ottamatta jättäminen preserves not have without implying withdrawal from ongoing treatment only. toivoo preserves wishes.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-010",
        "classification": "A_B_AGREE",
        "candidate_fi": "Onko tällä henkilöllä jokin näistä terveysongelmista?",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical A/B wording matches the question and health-problems scope.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-011",
        "classification": "A_B_AGREE",
        "candidate_fi": "Syöpä",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical plain equivalent of Cancer.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-012",
        "classification": "SELECT_A",
        "candidate_fi": "Sydämen tai verenkierron ongelmat",
        "meaningful_difference": "A keeps heart or circulation as separate problem nouns. B compounds Sydän- tai verenkierto-ongelmat.",
        "source_fidelity_rationale": "Heart or circulation problems is two alternatives plus problems. A's wording keeps that structure without compounding.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-013",
        "classification": "A_B_AGREE",
        "candidate_fi": "Munuaisongelmat",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical plain equivalent of Kidney problems.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-014",
        "classification": "COMBINE_A_B",
        "candidate_fi": "Toimintakyky on heikentynyt tavanomaisissa toimissa, ja terveys heikkenee.",
        "meaningful_difference": "usual: A tavallisissa vs B tavanomaisissa. health: A terveydentila vs B terveys.",
        "source_fidelity_rationale": "Recorded toimintakyky on heikentynyt is kept with tavanomaisissa toimissa. Source says health is getting poorer, not health condition.",
        "remaining": "",
        "human_decision_refs": ["less able to manage usual activities: toimintakyky on heikentynyt"],
    },
    {
        "unit_id": "S4A-2026-015",
        "classification": "SELECT_A",
        "candidate_fi": "Sydämen vajaatoiminta tai sydämen verisuonisairaus. Hengenahdistusta tai rintakipua levätessä, liikkuessa tai kävellessä muutaman askeleen.",
        "meaningful_difference": "when resting: A levätessä vs B levossa. walking a few steps: word order differs; first sentence is identical.",
        "source_fidelity_rationale": "when resting is a verbal circumstance (levätessä). Heart failure or heart blood vessel disease and the three activity alternatives are preserved.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-016",
        "classification": "SELECT_B",
        "candidate_fi": "Munuaiset eivät toimi hyvin; yleinen terveys heikkenee.",
        "meaningful_difference": "A yleinen terveydentila vs B yleinen terveys.",
        "source_fidelity_rationale": "general health is terveys, not terveydentila. Negation of kidneys working well is identical.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-017",
        "classification": "SELECT_B",
        "candidate_fi": "Ei ole riittävän hyväkuntoinen syöpähoitoon, tai hoito on oireiden helpottamiseksi.",
        "meaningful_difference": "A adds hoidon tarkoituksena on lievittää. B keeps treatment is to help with symptoms as hoito on oireiden helpottamiseksi.",
        "source_fidelity_rationale": "Recorded not-well-enough wording is kept. The or-alternative is treatment for helping symptoms, not an added purpose-clause.",
        "remaining": "",
        "human_decision_refs": ["not well enough for cancer treatment: ei ole riittävän hyväkuntoinen syöpähoitoon"],
    },
    {
        "unit_id": "S4A-2026-018",
        "classification": "SELECT_B",
        "candidate_fi": "Jalkaongelmia huonon verenkierron vuoksi; leikkaus ei ole mahdollinen.",
        "meaningful_difference": "A Huonosta verenkierrosta johtuvia jalkaongelmia vs B Jalkaongelmia huonon verenkierron vuoksi. Impossibility is identical.",
        "source_fidelity_rationale": "English order is leg problems due to poor circulation. B keeps that order and the impossibility of surgery.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-019",
        "classification": "SELECT_B",
        "candidate_fi": "Munuaisdialyysin lopettaminen tai palliatiivisen hoidon valitseminen dialyysin aloittamisen sijaan.",
        "meaningful_difference": "A adds hoito to dialysis twice. B has kidney dialysis then dialysis, matching the source.",
        "source_fidelity_rationale": "Stopping kidney dialysis or choosing palliative care instead of starting dialysis. Do not add treatment where the source says dialysis.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-020",
        "classification": "SELECT_B",
        "candidate_fi": "Dialyysin lopettaminen tai aloittamatta jättäminen",
        "meaningful_difference": "A Dialyysihoidon vs B Dialyysin. Stopping or not starting is otherwise the same.",
        "source_fidelity_rationale": "Source says dialysis, not dialysis treatment. Stopping or not starting are both preserved.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-021",
        "classification": "A_B_AGREE",
        "candidate_fi": "Dementia tai hauraus",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical A/B wording. Dementia or frailty alternatives preserved.",
        "remaining": "Frailty/hauraus was discussed before G1 without a recorded final human term. Working synthesis uses the agreed A/B wording; no term is invented as approved.",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-022",
        "classification": "A_B_AGREE",
        "candidate_fi": "Hengitysongelmat",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical plain equivalent of Respiratory problems.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-023",
        "classification": "A_B_AGREE",
        "candidate_fi": "Maksaongelmat",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical plain equivalent of Liver problems.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-024",
        "classification": "A_B_AGREE",
        "candidate_fi": "Ei pysty pukeutumaan, kävelemään tai syömään ilman apua.",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical preservation of unable, the three activities, and without help.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-025",
        "classification": "COMBINE_A_B",
        "candidate_fi": "Vointi on huonompi pitkäaikaisten keuhko-ongelmien yhteydessä. Hengenahdistusta levätessä, liikkuessa tai kävellessä muutaman askeleen silloinkin, kun rintakehä on parhaimmillaan.",
        "meaningful_difference": "More unwell: A huonontunut vs B huonompi. chest: A keuhkojen tilanne vs B rintakehä. resting: A levätessä vs B levossa.",
        "source_fidelity_rationale": "More unwell is a comparative state (huonompi), not necessarily a completed deterioration. chest is rintakehä, not a lung-status paraphrase. when resting stays verbal, aligned with S4A-2026-015.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-026",
        "classification": "COMBINE_A_B",
        "candidate_fi": "Kuluneen vuoden aikana pahentuneita maksaongelmia, joihin liittyy lisäongelmia, kuten:",
        "meaningful_difference": "A is a noun-phrase list header with seuraavia. B is a full sentence with kuten. List-item grammar in 027-031 differs.",
        "source_fidelity_rationale": "Worsening liver problems in the past year with complications like: is a list header. A time-fronted noun phrase plus kuten introduces the following examples without adding seuraavia.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-027",
        "classification": "SELECT_A",
        "candidate_fi": "nesteen kertymistä vatsaan",
        "meaningful_difference": "A partitive kertymistä vs B nominative kertyminen.",
        "source_fidelity_rationale": "List example under complications like; partitive matches an example noun rather than a heading.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-028",
        "classification": "SELECT_A",
        "candidate_fi": "ajoittaista sekavuutta",
        "meaningful_difference": "A ajoittaista sekavuutta vs B ajoittainen sekavuus.",
        "source_fidelity_rationale": "being confused at times is an example in the complications list; partitive matches that role. Delirium is not added.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-029",
        "classification": "A_B_AGREE",
        "candidate_fi": "munuaiset eivät toimi hyvin",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical negation of kidneys working well.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-030",
        "classification": "SELECT_A",
        "candidate_fi": "infektioita",
        "meaningful_difference": "A infektioita vs B infektiot.",
        "source_fidelity_rationale": "infections is a list example; partitive matches complications like.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-031",
        "classification": "SELECT_A",
        "candidate_fi": "verenvuotoa ruokatorvesta",
        "meaningful_difference": "A verenvuotoa vs B verenvuoto. gullet/ruokatorvi is the same.",
        "source_fidelity_rationale": "bleeding from the gullet is a list example; partitive matches the header.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-032",
        "classification": "A_B_AGREE",
        "candidate_fi": "Syö ja juo vähemmän; nielemisvaikeuksia.",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical preservation of eating and drinking less and swallowing difficulty.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-033",
        "classification": "SELECT_B",
        "candidate_fi": "Tarvitsee käyttää happea suuren osan päivästä ja yöstä.",
        "meaningful_difference": "A adds lisähappea and drops use. B keeps needs to use oxygen.",
        "source_fidelity_rationale": "Source is use oxygen, not supplemental oxygen. Day and night duration is kept.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-034",
        "classification": "SELECT_B",
        "candidate_fi": "Virtsarakon ja suolen hallinta on heikkoa.",
        "meaningful_difference": "A paraphrases as difficulty holding urine and stool. B keeps poor control of bladder and bowels.",
        "source_fidelity_rationale": "poor control of bladder and bowels is organ control, not only continence-holding difficulty.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-035",
        "classification": "SELECT_B",
        "candidate_fi": "On tarvinnut sairaalassa hoitoa hengityskoneella.",
        "meaningful_difference": "A compounds hengityskonehoitoa. B keeps treatment with a breathing machine in hospital.",
        "source_fidelity_rationale": "T-013 hengityskone is applied. treatment with a breathing machine in hospital is location plus instrument, not a fused treatment-type.",
        "remaining": "",
        "human_decision_refs": ["T-013"],
    },
    {
        "unit_id": "S4A-2026-036",
        "classification": "COMBINE_A_B",
        "candidate_fi": "Ei pysty viestimään puhumalla; ei vastaa juurikaan muihin ihmisiin.",
        "meaningful_difference": "communicate: A viestiä vs B kommunikoida. not responding: A reagoi vain vähän vs B ei vastaa juurikaan.",
        "source_fidelity_rationale": "Plain viestiä preserves communicate without a loanword. ei vastaa preserves the negation of responding much.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-037",
        "classification": "A_B_AGREE",
        "candidate_fi": "Toistuvia kaatumisia; reisiluun murtuma.",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical Frequent falls; fractured femur.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-038",
        "classification": "A_B_AGREE",
        "candidate_fi": "Toistuvia infektioita; keuhkokuume",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical Frequent infections; pneumonia.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-039",
        "classification": "A_B_AGREE",
        "candidate_fi": "Hermoston ongelmat",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical Nervous system problems.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-040",
        "classification": "A_B_AGREE",
        "candidate_fi": "Muut terveydentilat",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical Other conditions in this health-tool context.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-041",
        "classification": "SELECT_A",
        "candidate_fi": "Fyysinen terveys ja mielenterveys heikkenevät.",
        "meaningful_difference": "A Fyysinen terveys vs B Ruumiillinen terveys.",
        "source_fidelity_rationale": "physical and mental health as a pair: fyysinen terveys ja mielenterveys, both getting worse.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-042",
        "classification": "SELECT_A",
        "candidate_fi": "Ihmiset, joiden terveydentila on heikentynyt ja joilla on muita elinikää lyhentäviä fyysisiä sairauksia, mielenterveyden sairauksia tai terveydentiloja. Hoitoa ei ole saatavilla tai se ei tehoa hyvin.",
        "meaningful_difference": "A splits physical illnesses, mental illnesses or health conditions. B uses ruumiillisia tai henkisiä sairauksia.",
        "source_fidelity_rationale": "physical or mental illnesses or health conditions is three-way. henkisiä sairauksia is a poorer reading of mental illnesses. T-002 and less-well wording are in both; A's illness/condition split is closer.",
        "remaining": "",
        "human_decision_refs": ["T-002", "less well: terveydentila on heikentynyt"],
    },
    {
        "unit_id": "S4A-2026-043",
        "classification": "SELECT_A",
        "candidate_fi": "Enemmän ongelmia puhumisessa ja viestimisessä; nieleminen vaikeutuu.",
        "meaningful_difference": "A viestimisessä vs B kommunikoinnissa. Swallowing getting worse is the same.",
        "source_fidelity_rationale": "speaking and communicating kept as two activities; plain viestiä matches S4A-2026-036. Swallowing is getting worse is preserved.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-044",
        "classification": "A_B_AGREE",
        "candidate_fi": "Mitä voimme tehdä tämän henkilön ja hänen perheensä auttamiseksi.",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical we / this person and their family.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-045",
        "classification": "SELECT_B",
        "candidate_fi": "Rintakehän infektioita tai keuhkokuume; hengitysongelmia.",
        "meaningful_difference": "A medicalizes chest infections as alempien hengitysteiden infektioita. B keeps rintakehän infektioita.",
        "source_fidelity_rationale": "Source says chest infections, not lower-respiratory-tract infections. Pneumonia and breathing problems remain alternatives/additions as in the source.",
        "remaining": "Plain Finnish rintakehän infektiot is a close rendering of chest infections; it is slightly calqued and is recorded, not silently replaced with a clinical class.",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-046",
        "classification": "COMBINE_A_B",
        "candidate_fi": "Aloita keskustelu henkilön ja hänen perheensä tai hänestä huolehtivan ihmisen kanssa siitä, mitä apua tarvitaan nyt ja miksi suunnitelmien tekeminen on tärkeää siltä varalta, että asiat muuttuvat.",
        "meaningful_difference": "carer: A huolehtivan ihmisen vs B hoitavan läheisen. help: A mitä apua vs B millaista apua. things: A tilanne vs B asiat.",
        "source_fidelity_rationale": "family or carer stays aligned with S4A-2026-006. help needed now is what help is needed, not what kind. in case things change is asiat, not situation.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-047",
        "classification": "COMBINE_A_B",
        "candidate_fi": "Jatkuva toimintarajoite, johon liittyy lisääntyviä fyysisen terveyden ja/tai mielenterveyden ongelmia yhden tai useamman aivohalvauksen jälkeen.",
        "meaningful_difference": "with: A sekä vs B johon liittyy. physical health: A fyysisen terveyden vs B ruumiillisia.",
        "source_fidelity_rationale": "Ongoing disability with increasing physical and/or mental health problems. johon liittyy preserves with. fyysisen terveyden ja/tai mielenterveyden ongelmia preserves both health arms. one or more strokes kept.",
        "remaining": "Stroke/aivohalvaus scope was a T1 SAMI item; no new term is invented here.",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-048",
        "classification": "SELECT_B",
        "candidate_fi": "Pyydä apua ja neuvoa sairaanhoitajalta, lääkäriltä, sosiaalityöntekijältä tai muulta henkilökunnalta, jos henkilö tai perhe tarvitsee hoitonsa ja tukensa tarkastelua.",
        "meaningful_difference": "A adds uudelleen to review. B keeps needs a review of their care and support. nurse/doctor/social worker/other staff are the same.",
        "source_fidelity_rationale": "A review is not necessarily a re-review. Staff alternatives and person or family agency are preserved.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-049",
        "classification": "COMBINE_A_B",
        "candidate_fi": "Tarkastelemme henkilön lääkkeitä ja muita hoitoja, jotta voimme antaa parasta hoitoa. Kokonaisvaltainen hoito kattaa oireet sekä tunne-elämään, sosiaaliseen elämään, toimintakykyyn, talouteen, henkisiin ja hengellisiin kysymyksiin sekä kulttuuriin liittyvät ongelmat.",
        "meaningful_difference": "A adds mahdollista to best care and keeps henkisiin ja hengellisiin. B has parasta hoitoa but only hengelliset for spiritual.",
        "source_fidelity_rationale": "T-016 kokonaisvaltainen hoito. the best care is not best possible. spiritual is not narrowed to religion only; henkinen ja hengellinen keeps existential and religious readings. medicines and other treatments remain distinct.",
        "remaining": "spiritual remains a genuine wording uncertainty; dual henkinen/hengellinen is a source-fidelity choice, not an approved glossary term.",
        "human_decision_refs": ["T-016"],
    },
    {
        "unit_id": "S4A-2026-050",
        "classification": "A_B_AGREE",
        "candidate_fi": "Pyydä asiantuntija-apua, jos oireita tai ongelmia on vaikea hallita.",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical specialist help without adding a medical-consultant requirement.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-051",
        "classification": "SELECT_B",
        "candidate_fi": "Hoitosuunnitelmat jaetaan henkilökunnalle, jonka tarvitsee nähdä ne, ja ne pidetään ajan tasalla.",
        "meaningful_difference": "B makes ne the explicit subject of kept up to date. A leaves the second verb implicit.",
        "source_fidelity_rationale": "Care plans are shared and kept up to date. Explicit ne keeps the plans as the thing updated.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-2026-052",
        "classification": "A_B_AGREE",
        "candidate_fi": "SPICT – 4ALL 2026",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical untranslated verbatim instrument line.",
        "remaining": "",
        "human_decision_refs": [],
    },
    {
        "unit_id": "S4A-REQ-2026-001",
        "classification": "A_B_AGREE",
        "candidate_fi": "Maksansiirto ei ole mahdollinen.",
        "meaningful_difference": "",
        "source_fidelity_rationale": "Identical A liver transplant is not possible. Noncanonical unresolved requirement; not promoted into canonical membership.",
        "remaining": "Unresolved canonical omission and publication-blocking status remain. This is translation evidence only.",
        "human_decision_refs": [],
    },
)
